"""add processed and total files to scan job

Revision ID: a75bc3fa0c4a
Revises: c6fc791e855d
Create Date: 2026-03-13 12:27:19.779628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a75bc3fa0c4a'
down_revision: Union[str, None] = 'c6fc791e855d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('processed_files', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scan_jobs', sa.Column('total_files', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_jobs', 'total_files')
    op.drop_column('scan_jobs', 'processed_files')
    # ### end Alembic commands ###
