"""initial

Revision ID: e4fa5123283f
Revises: 
Create Date: 2026-03-13 10:19:56.153809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e4fa5123283f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('github_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('github_repo_url', sa.String(), nullable=False),
    sa.Column('github_repo_name', sa.String(), nullable=False),
    sa.Column('github_repo_owner', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_status', sa.String(), nullable=False),
    sa.Column('total_functions', sa.Integer(), nullable=False),
    sa.Column('total_endpoints', sa.Integer(), nullable=False),
    sa.Column('total_external_services', sa.Integer(), nullable=False),
    sa.Column('documentation_coverage_score', sa.Float(), nullable=False),
    sa.Column('security_score', sa.Float(), nullable=False),
    sa.Column('architectural_narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'github_repo_url', name='uq_user_repo_url')
    )
    op.create_table('diagrams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('diagram_type', sa.String(), nullable=False),
    sa.Column('entry_point_path', sa.String(), nullable=True),
    sa.Column('mermaid_markup', sa.Text(), nullable=False),
    sa.Column('render_attempts', sa.Integer(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('rendered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('function_name', sa.String(), nullable=False),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('parameter_descriptions', sa.JSON(), nullable=True),
    sa.Column('return_description', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('big_o_estimate', sa.String(), nullable=True),
    sa.Column('cyclomatic_complexity', sa.Integer(), nullable=True),
    sa.Column('maintainability_index', sa.Float(), nullable=True),
    sa.Column('lines_of_code', sa.Integer(), nullable=True),
    sa.Column('handles_pii', sa.Boolean(), nullable=False),
    sa.Column('is_entry_point', sa.Boolean(), nullable=False),
    sa.Column('is_unprotected', sa.Boolean(), nullable=False),
    sa.Column('decorators', sa.JSON(), nullable=False),
    sa.Column('callers', sa.JSON(), nullable=False),
    sa.Column('callees', sa.JSON(), nullable=False),
    sa.Column('external_services_called', sa.JSON(), nullable=False),
    sa.Column('db_models_queried', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('llm_model_used', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'file_path', 'function_name', name='uq_repo_file_func')
    )
    op.create_table('external_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('calling_functions', sa.JSON(), nullable=False),
    sa.Column('http_methods', sa.JSON(), nullable=False),
    sa.Column('is_internal_microservice', sa.Boolean(), nullable=False),
    sa.Column('is_high_coupling', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_hashes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('sha256_hash', sa.String(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'file_path', name='uq_repo_file_path')
    )
    op.create_table('scan_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_message', sa.String(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.String(), nullable=False),
    sa.Column('endpoint_path', sa.String(), nullable=True),
    sa.Column('function_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_flags')
    op.drop_table('scan_jobs')
    op.drop_table('file_hashes')
    op.drop_table('external_services')
    op.drop_table('documentations')
    op.drop_table('diagrams')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
